update

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -26,6 +26,14 @@ jobs:
         run: |
           az webapp config appsettings set --name nonsoresumeapp --resource-group resumeresourcegroup --settings ENABLE_ORYX_BUILD=false   
       
+      - name: Validate File Path
+        run: |
+            if [ ! -f "/home/runner/work/Serverless-resume-app/Serverless-resume-app/functionapp.zip" ]; then
+              echo "File not found!"
+              exit 1
+            fi
+             
+      
       # Deploy Azure Function App
       - name: Deploy Azure Function App
         run: |
